before:
  hooks:
    - go generate
    - go mod tidy
builds:
  - id: itd
    env:
      - CGO_ENABLED=0
    binary: itd
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - riscv64
    goarm:
      - 7
  - id: itctl
    env:
      - CGO_ENABLED=0
    main: ./cmd/itctl
    binary: itctl
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      -  7
archives:
  - name_template: >-
       {{- .ProjectName }}-{{.Version}}-{{.Os}}-
       {{- if eq .Arch "386" }}i386
       {{- else if eq .Arch "amd64" }}x86_64
       {{- else if eq .Arch "arm64" }}aarch64
       {{- else }}{{.Arch}}
       {{- end }}
    files:
      - LICENSE
      - README.md
      - itd.toml
      - itd.service
    allow_different_binary_count: true
nfpms:
  - id: itd
    file_name_template: >-
        {{- .PackageName }}-{{.Version}}-{{.Os}}-
        {{- if eq .Arch "386" }}i386
        {{- else if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "arm64" }}aarch64
        {{- else }}{{.Arch}}
        {{- end }}
    description: "Companion daemon for the InfiniTime firmware on the PineTime smartwatch"
    homepage: 'https://gitea.elara.ws/Elara6331/itd'
    maintainer: 'Elara Ivy <elara@elara.ws>'
    license: GPLv3
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    dependencies:
      - dbus
      - bluez
    contents:
      - src: itd.toml
        dst: /etc/itd.toml
        type: "config|noreplace"
      - src: itd.service
        dst: /usr/lib/systemd/user/itd.service
        file_info:
          mode: 0755
aurs:
  - name: itd-bin
    homepage: 'https://gitea.elara.ws/Elara6331/itd'
    description: "Companion daemon for the InfiniTime firmware on the PineTime smartwatch"
    maintainers:
      - 'Elara Ivy <elara@elara.ws>'
    license: GPLv3
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/itd-bin.git'
    provides:
      - itd
      - itctl
    conflicts:
      - itd
      - itctl
    depends:
      - dbus
      - bluez
    package: |-
      # binaries
      install -Dm755 ./itd "${pkgdir}/usr/bin/itd"
      install -Dm755 ./itctl "${pkgdir}/usr/bin/itctl"

      # service
      install -Dm644 "./itd.service" ${pkgdir}/usr/lib/systemd/user/itd.service

      # config
      install -Dm644 "./itd.toml" ${pkgdir}/etc/itd.toml
      
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/itd/LICENSE"
release:
  gitea:
    owner: Elara6331
    name: itd
gitea_urls:
  api: 'https://gitea.elara.ws/api/v1/'
  download: 'https://gitea.elara.ws'
  skip_tls_verify: false
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
