# This is temporary, it is to show a notice
# to people still using the old config
cfg.version = 2

[socket]
    path = "/tmp/itd/socket"

[conn]
    reconnect = true

[conn.whitelist]
    enabled = false
    devices = []

[on.connect]
    notify = true

[on.reconnect]
    notify = true
    setTime = true

[notifs.translit]
    use = ["eASCII", "Russian", "Emoji"]

[notifs.ignore]
    sender = []
    summary = ["InfiniTime"]
    body = []

[music]
    vol.interval = 5

