name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: any
    container: goreleaser/goreleaser
    steps:
      - uses: actions/checkout@v4
      - name: goreleaser release
        run: goreleaser release
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
