name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: https://github.com/actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Run GoReleaser
        uses: https://github.com/goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: release --clean
        env:
          AUR_KEY: ${{ secrets.AUR_KEY }}
          GITEA_TOKEN: ${{ forgejo.token }}
          GORELEASER_FORCE_TOKEN: gitea
